In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("monte_monte_2.csv")

In [3]:
df.describe()

,GameMe0,GameMe1,GameOp0,GameOp1,ViewBlue0,ViewRed0,ViewAlive0,ViewAlive1,Side,ActionIndex
count,139594.000000,139594.000000,139594.000000,139594.000000,139594.000000,139594.000000,139594.000000,139594.000000,139594.000000,139594.000000
mean,12.782541,10.668797,2.324147,4.806668,12.782541,10.668797,2.324147,4.806668,0.482893,0.630092
std,2.068821,3.234091,2.229421,3.404238,2.068821,3.234091,2.229421,3.404238,0.499709,0.482781
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,12.000000,9.000000,1.000000,2.000000,12.000000,9.000000,1.000000,2.000000,0.000000,0.000000
50%,13.000000,11.000000,2.000000,5.000000,13.000000,11.000000,2.000000,5.000000,0.000000,1.000000
75%,14.000000,13.000000,3.000000,7.000000,14.000000,13.000000,3.000000,7.000000,1.000000,1.000000
max,15.000000,15.000000,15.000000,15.000000,15.000000,15.000000,15.000000,15.000000,1.000000,1.000000

In [4]:
set(df.ActionDirection)

{'-1', '-4', '1', '4', 'WIN'}

In [5]:
df[['GameMe0', 'GameMe1', 'ActionIndex']]

        GameMe0  GameMe1  ActionIndex
0            13       14            0
1            14       13            1
2            12       14            1
3            14        9            0
4            12       10            1
5            15        9            1
6            12       14            1
7            15        8            1
8            12       10            0
9            15        4            0
10           13       10            1
11           14        4            1
12           13        6            0
13           14        8            1
14            9        6            1
15           14        4            1
16           13       14            0
17           14       13            1
18           12       14            1
19           14        9            1
20           12       15            0
21           14        8            1
22           13       15            1
23           14       13            0
24           14       13            0
25           15       13            0
26           15       13            1
27           11       13            0
28           15       14            1
29           15       13            1
...         ...      ...          ...
139564       15       13            1
139565       14        8            1
139566       15       14            0
139567       13       14            1
139568       14       13            1
139569       13       15            0
139570       14       12            1
139571       14       15            0
139572       14       13            1
139573       10       15            1
139574       14        9            0
139575       10       14            0
139576       13        9            1
139577       11       14            1
139578       14       13            0
139579       14       13            1
139580       15       13            1
139581       14        9            0
139582       15       14            1
139583       10        9            1
139584       15       10            1
139585       10       13            1
139586       15       11            1
139587       10       12            0
139588       15        7            1
139589       14       12            1
139590       15        6            0
139591       14       13            0
139592       14        6            0
139593       15       13            0

[139594 rows x 3 columns]

In [6]:
X = df[['GameMe0', 'GameMe1']].as_matrix()

In [7]:
Y = df.ActionIndex

In [8]:
df['TargetPos'] = [X.item(pos) for pos in enumerate(Y)]

In [9]:
from sklearn.linear_model import LogisticRegression
m = LogisticRegression()
df['ActionDirectionAsInt'] = df.ActionDirection.map({'-1': 0, '-4': 1, '1': 2, '4': 3, 'WIN': 4})
xs = df[['TargetPos', 'ActionDirectionAsInt']]
ys = df.ActionIndex
m.fit(xs[::2], ys[::2])
m.score(xs[1::2], ys[1::2])

0.63901027264782151

In [10]:
from sklearn.svm import SVC
m = SVC()
m.fit(xs[::200], ys[::200])
m.score(xs[1::200], ys[1::200])

0.70630372492836679

In [11]:
df['TheOtherPos'] = df.GameMe0 + df.GameMe1 - df.TargetPos

In [12]:
xs = df[['TargetPos', 'ActionDirectionAsInt', 'TheOtherPos']]
m = LogisticRegression()
m.fit(xs[::2], ys[::2])
m.score(xs[1::2], ys[1::2])

0.76011862974053324

In [13]:
m = SVC()
m.fit(xs[::200], ys[::200])
m.score(xs[1::200], ys[1::200])

0.7435530085959885

In [19]:
df['TargetPosX'] = df.TargetPos % 4
df['TargetPosY'] = df.TargetPos // 4
df['TheOtherPosX'] = df.TheOtherPos % 4
df['TheOtherPosY'] = df.TheOtherPos // 4
df['TargetPosStr'] = df.TargetPos.astype(str)
df['TheOtherPosStr'] = df.TheOtherPos.astype(str)

xs = df[['TargetPosX', 'TargetPosY', 'TargetPosStr', 'ActionDirection', 'TheOtherPosX', 'TheOtherPosY', 'TheOtherPosStr']]
xs = pd.get_dummies(xs)
xs.head()

,TargetPosX,TargetPosY,TheOtherPosX,TheOtherPosY,TargetPosStr_0,TargetPosStr_1,TargetPosStr_10,TargetPosStr_11,TargetPosStr_12,TargetPosStr_13,...,TheOtherPosStr_14,TheOtherPosStr_15,TheOtherPosStr_2,TheOtherPosStr_3,TheOtherPosStr_4,TheOtherPosStr_5,TheOtherPosStr_6,TheOtherPosStr_7,TheOtherPosStr_8,TheOtherPosStr_9
0,1,3,2,3,0,0,0,0,0,1,...,1,0,0,0,0,0,0,0,0,0
1,1,3,2,3,0,0,0,0,0,1,...,1,0,0,0,0,0,0,0,0,0
2,2,3,0,3,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,2,3,1,2,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
4,2,2,0,3,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [21]:
m = LogisticRegression()
m.fit(xs[::2], ys[::2])
m.score(xs[1::2], ys[1::2])

0.77292720317492158

In [32]:
list(sorted(zip(m.coef_[0], xs.columns)))

[(-6.594417914953131, 'ActionDirection_WIN'),
 (-1.6104381213937817, 'TargetPosStr_4'),
 (-1.3343875120951065, 'TargetPosY'),
 (-1.2811414299586097, 'TargetPosStr_7'),
 (-1.0310578335359317, 'TheOtherPosStr_2'),
 (-0.71491026856160744, 'TheOtherPosStr_5'),
 (-0.53984804300358369, 'TheOtherPosStr_4'),
 (-0.45186745458742483, 'TheOtherPosStr_3'),
 (-0.4359920642648229, 'TargetPosStr_8'),
 (-0.40854982278057628, 'TheOtherPosStr_6'),
 (-0.39765809896599646, 'TargetPosStr_0'),
 (-0.39073310047179555, 'TheOtherPosStr_0'),
 (-0.30237687950919473, 'TheOtherPosStr_12'),
 (-0.20459266975093424, 'TargetPosStr_12'),
 (-0.19343291800014367, 'TheOtherPosX'),
 (-0.14281672789437808, 'TargetPosX'),
 (-0.10283994370929878, 'TargetPosStr_11'),
 (-0.091955265935825925, 'TargetPosStr_1'),
 (-0.049485385268500041, 'TargetPosStr_13'),
 (-0.012984779580838476, 'TheOtherPosStr_9'),
 (0.013204400994516224, 'TargetPosStr_3'),
 (0.078974503237649374, 'TheOtherPosStr_1'),
 (0.083749038442495052, 'TheOtherPosStr_13'),
 (0.095124425456153919, 'TargetPosStr_2'),
 (0.12525027846929851, 'TargetPosStr_14'),
 (0.14869830108608689, 'TheOtherPosStr_10'),
 (0.15971770429219273, 'TargetPosStr_9'),
 (0.18829531174360711, 'TheOtherPosStr_7'),
 (0.20914625134656295, 'TheOtherPosStr_8'),
 (0.21183796695458168, 'TargetPosStr_15'),
 (0.25679422145635766, 'TheOtherPosStr_15'),
 (0.29400868212464198, 'TargetPosStr_10'),
 (0.29636017802510434, 'TheOtherPosStr_14'),
 (0.62549619237765064, 'ActionDirection_4'),
 (0.66978896227904894, 'TargetPosStr_5'),
 (0.7937235689043004, 'TheOtherPosStr_11'),
 (0.80858375087755463, 'TargetPosStr_6'),
 (1.1791357102787912, 'ActionDirection_1'),
 (1.2090207433353255, 'ActionDirection_-1'),
 (1.7841784611389362, 'ActionDirection_-4'),
 (1.8057335332833242, 'TheOtherPosY')]

In [31]:
m.coef_[0]

array([-0.14281673, -1.33438751, -0.19343292,  1.80573353, -0.3976581 ,
       -0.09195527,  0.29400868, -0.10283994, -0.20459267, -0.04948539,
        0.12525028,  0.21183797,  0.09512443,  0.0132044 , -1.61043812,
        0.66978896,  0.80858375, -1.28114143, -0.43599206,  0.1597177 ,
        1.20902074,  1.78417846,  1.17913571,  0.62549619, -6.59441791,
       -0.3907331 ,  0.0789745 ,  0.1486983 ,  0.79372357, -0.30237688,
        0.08374904,  0.29636018,  0.25679422, -1.03105783, -0.45186745,
       -0.53984804, -0.71491027, -0.40854982,  0.18829531,  0.20914625,
       -0.01298478])

In [14]:
df.tail()

,GameMe0,GameMe1,GameOp0,GameOp1,ViewBlue0,ViewRed0,ViewAlive0,ViewAlive1,Side,ActionIndex,ActionDirection,Winner,TargetPos,ActionDirectionAsInt,TheOtherPos
139589,14,12,0,9,14,12,0,9,1,1,1,LOSE,12,2,14
139590,15,6,1,2,15,6,1,2,0,0,-1,LOSE,15,0,6
139591,14,13,1,9,14,13,1,9,1,0,1,LOSE,14,2,13
139592,14,6,0,2,14,6,0,2,0,0,-4,LOSE,14,1,6
139593,15,13,5,9,15,13,5,9,1,0,-1,LOSE,15,0,13